### ISSUE TITLE
Automatic Bluemix deploy button not working

### ISSUE THREAD

**Issue by max-at-brili** [ibm-cds-labs/parse-on-bluemix#6]
When I press the button to "Deploy to Bluemix" from the github I am brought to the Bluemix site and it correctly identifies the parse-server github repo, and it forces me to login again (See the first picture). 

![bm_deploy_err1](https://cloud.githubusercontent.com/assets/22665252/19162502/1df96d96-8bc6-11e6-92bb-f51179536bd2.jpeg)

Once I login it displays "Unable to access the source Git repo" and the "Deploy" button is unavailable (See second picture):

![bm_deploy_err2](https://cloud.githubusercontent.com/assets/22665252/19162604/843e7fd8-8bc6-11e6-8270-a3298a820bbd.jpeg)

**Comment by ptitzler** [comment]
This seems to be a temporary glitch in Bluemix and/or github. Please try again. I was just able to launch the deployment without any issues.
